name: jest test
run-name: ${{ github.actor }} running tests
on: [push]
jobs:
  run-defined-frontend-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - name: Run tests
        run: npx stryker run
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.1.1
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.TEST_COV_ID }}
        with:
          coverageCommand: npx stryker run
      - run: cc-test-reporter before-build
      - run: cc-test-reporter after-build