
name: build
on:
  push
jobs:
  test:      
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: 20.x
    - run: npm install -g yarn
    - run: yarn install
  coverage:
    needs: [ test ]
    name: coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '12'
    - run: npm install -g yarn
    - run: yarn install
    - uses: paambaati/codeclimate-action@v8.0.0
      env:
        CC_TEST_REPORTER_ID: 384d0da08a5564e84812aec660494dc57048e411dd5c86cb6ecf5926dee21b5b
      with:
        coverageCommand: 	npx jest --coverage
